// This file is generated by the FlutterFire CLI.
// You should not modify it by hand.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyDSDh6PqnOEZsfxdsO3VMt0mlzZoBIn-mE',
      appId: '1:924258829246:android:dccb69e0d3e604e8142fef',
      messagingSenderId: '924258829246',
      projectId: 'product-prize',
      storageBucket: 'product-prize.firebasestorage.app',
      // The following fields are not present in google-services.json
      authDomain: '',
      measurementId: '',
    );
  }
}
